# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Keystone
description:        An Open Framework for Architecting TEEs
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
#permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
//url:                "https://docs.jekyll.plus"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
#logo: https://keystone-enclave.org/uploads/icon-transparent.png

navbar:
    sticky:         true
    search:         false

# Default author settings
author:
    name:           Keystone Team
    title:          Team
    avatar:         icon-transparent.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    dayeol:
      name:         Dayeol Lee
      title:        UC Berkeley
      avatar:       team/dayeol.png
      website:      https://dayeol.github.io
    dkohlbre:
      name:         David Kohlbrenner
      title:        University of Washington 
      avatar:       team/dkohlbre.jpg
      website:      https://dkohlbre.com
    shweta:
      name:         Shweta Shinde
      title:        ETH Zurich
      avatar:       team/shweta.jpg
      website:      https://n.ethz.ch/~sshivaji/
    dawn:
      name:         Dawn Song
      title:        UC Berkeley
      avatar:       team/dawn.png
      website:      https://people.eecs.berkeley.edu/~dawnsong/
    krste:
      name:         Krste Asanovic
      title:        UC Berkeley 
      avatar:       team/krste.png
      website:      http://people.eecs.berkeley.edu/~krste/
    alex:
      name:         Alex Thomas
      title:        UC Berkeley
      avatar:       team/alex.jpeg
    stephan:
      name:         Stephan Kaminsky
      title:        UC Berkeley
      avatar:       team/stephan.jpeg
    gui:
      name:         Gui Andrade
      title:        UC Berkeley
      avatar:       team/gui.jpg
    cathy:
      name:         Catherine Lu
      title:        UC Berkeley
      avatar:       team/cathylu.png

# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github: https://github.com/keystone-enclave
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter: https://twitter.com/keystoneenclave
    vimeo:
    youtube:

# Share button
share:
    post:           false # Display share buttons on a post page
    doc:            false # Display share buttons on a doc page
    #titter:         true # Enable by adding Twitter handle
    facebook:       false # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
  copyright:      © 2021 Keystone Enclave. Powered by Jekyll and <a href="https://jekyllthemes.io/theme/docs-responsive-documentation-or-manual-jekyll-theme">Docs</a>
# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: true

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

twitter:
  username: keystoneenclave
  card: summary

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
    values:
      image: https://keystone-enclave.org/uploads/icon-transparent.png
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
      image: https://keystone-enclave.org/uploads/icon-transparent.png 
  #_docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
      image: https://keystone-enclave.org/uploads/icon-transparent.png

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false


