# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Keystone
description:        An Open Framework for Architecting TEEs
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
#permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
//url:                "https://docs.jekyll.plus"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: icon-transparent.png

navbar:
    sticky:         true
    search:         false

# Default author settings
author:
    name:           Keystone Team
    title:          Team
    avatar:         icon-transparent.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    dayeol:
      name:         Dayeol Lee
      title:        UC Berkeley (Ph.D. student)
      avatar:       team/dayeol.png
      website:      https://dayeol.github.io
    dkohlbre:
      name:         David Kohlbrenner
      title:        UC Berkeley (Postdoc)
      avatar:       team/dkohlbre.png
      website:      https://dkohlbre.com
    shweta:
      name:         Shweta Shinde
      title:        UC Berkeley (Postdoc)
      avatar:       team/shweta.jpg
      website:      https://people.eecs.berkeley.edu/~shwetas/
    dawn:
      name:         Dawn Song
      title:        UC Berkeley (Faculty)
      avatar:       team/dawn.png
      website:      https://people.eecs.berkeley.edu/~dawnsong/
    krste:
      name:         Krste Asanovic
      title:        UC Berkeley (Faculty)
      avatar:       team/krste.png
      website:      http://people.eecs.berkeley.edu/~krste/

# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github: https://github.com/keystone-enclave
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter: https://twitter.com/keystoneenclave
    vimeo:
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
  copyright:      © 2019 Keystone Enclave. Powered by Jekyll and <a href="https://jekyllthemes.io/theme/docs-responsive-documentation-or-manual-jekyll-theme">Docs</a>
# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
